spring:
  application:
    name: clsoftlab

  devtools:
    restart:
      enabled: true
#  db 생성 전이라면 아래 코드 주석을 해제해서 써주세요.
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# db 생선 전이라면 아래 코드를 주석처리 해주세요.
# db를 생성하셨다면 사용하신 db의 username과 비밀번호를 설정해주세요.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clsoftlab
    username: root 
    password: 1111